name: Deploy to UAT

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:

  deploy:

    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli
          echo y | sf plugins install sfdx-git-delta
          sf version

      - name: Authenticate to UAT
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > auth.txt
          sf org login sfdx-url \
            --sfdx-url-file auth.txt \
            --alias UAT

      - name: Generate Delta Package
        run: |
          sf sgd source delta \
            --from HEAD~1 \
            --to HEAD \
            --output-dir delta

      - name: Deploy Delta
        run: |
          sf project deploy start \
            --target-org UAT \
            --manifest delta/package/package.xml \
            --test-level RunRelevantTests \
            --wait 120