name: Validate Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:

  validate:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli
          sf version

      - name: Authenticate to UAT
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > auth.txt
          sf org login sfdx-url \
            --sfdx-url-file auth.txt \
            --alias UAT

      - name: Validate Deployment
        run: |
          sf project deploy validate \
            --target-org UAT \
            --source-dir force-app \
            --test-level RunLocalTests \
            --wait 120