name: Validate Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli
          echo y | sf plugins install sfdx-git-delta
          sf version
          sf plugins
          sf sgd source delta --help

      - name: Authenticate to UAT
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > auth.txt
          sf org login sfdx-url \
            --sfdx-url-file auth.txt \
            --alias UAT

      - name: Generate Delta Package
        run: |
          sf sgd source delta \
            --from origin/main \
            --to HEAD \
            --output-dir delta

      - name: Validate Deployment
        run: |
          sf project deploy validate \
            --target-org UAT \
            --manifest delta/package/package.xml \
            --test-level RunRelevantTests \
            --wait 120